"""
Centralized constants for TradeSeeker to eliminate magic numbers (PLR2004).
"""

# History & Retention
PORTFOLIO_STATE_FILE = "data/portfolio_state.json"
TRADE_HISTORY_FILE = "data/trade_history.json"
FULL_TRADE_HISTORY_FILE = "data/full_trade_history.json"
MAX_CYCLE_HISTORY = 50
MAX_TRADE_HISTORY_DISPLAY = 100
MAX_REPORT_ENTRIES = 50
PORTFOLIO_HISTORY_MAX_ENTRIES = 5000

# Cooldowns & Progress
DEFAULT_COOLDOWN_CYCLES = 3
MAX_DIRECTIONAL_COOLDOWN = 10
CAUTION_WIN_PROGRESS_THRESHOLD = 3
CONSECUTIVE_LOSS_THRESHOLD = 3
COUNTER_TREND_LOSS_THRESHOLD = 2
MIN_RELAXED_CYCLES = 3

# Thresholds & Rates
MAINTENANCE_MARGIN_RATE = 0.01
LOSS_STREAK_USD_THRESHOLD = 4.0
LOSS_STREAK_MAX_CAP_USD = 10000.0

# Timing
FILE_RETRY_DELAY = 0.1
TREND_FLIP_COOLDOWN_DEFAULT = 2
TREND_FLIP_HISTORY_WINDOW = 5
ROLLING_BIAS_WINDOW = 20

# Confidence & Bias Adjustments
CAUTION_PENALTY_MULTIPLIER = 0.90
CAUTION_ABSOLUTE_REDUCTION = 0.7
NEGATIVE_ROLLING_AVG_PENALTY_MULTIPLIER = 0.97
NEGATIVE_ROLLING_AVG_REDUCTION = 0.02
CONFIDENCE_FLOOR_MULTIPLIER = 0.90

# Erosion Levels (Percentage)
EROSION_THRESHOLD_MINOR = 20
EROSION_THRESHOLD_SIGNIFICANT = 50
EROSION_THRESHOLD_CRITICAL = 100

# Circuit Breaker & API
CIRCUIT_BREAKER_THRESHOLD = 5
CIRCUIT_BREAKER_TIMEOUT_S = 60
MAX_API_RETRIES = 3
MIN_KLINE_DATA_POINTS = 50
API_TIMEOUT_SECONDS = 10

# Technical Indicators
INDICATOR_HISTORY_DEFAULT = 10
VOLUME_WINDOW_SIZE = 20
VWAP_WINDOW_SIZE = 60
BB_SQUEEZE_THRESHOLD = 0.03
SPARKLINE_WINDOW = 24
ADX_STRONG_THRESHOLD = 40
ADX_MODERATE_THRESHOLD = 25
ADX_WEAK_THRESHOLD = 15

# Fibonacci Periods (Standard)
FIB_3 = 3
FIB_8 = 8
FIB_13 = 13
FIB_21 = 21
FIB_55 = 55

# Standard Indicator Periods & Thresholds
EMA_FAST = 20
EMA_MEDIUM = 50
EMA_SLOW = 100
EMA_LONG_TERM = 200
BB_STD_DEV_NORMAL = 2.0
BB_STD_DEV_WIDE = 2.5
VOLUME_RATIO_HIGH = 1.5
VOLUME_RATIO_LOW = 0.5
RSI_OVERBOUGHT = 70.0
RSI_OVERSOLD = 30.0
RSI_HTF_OVERBOUGHT = 70
RSI_THRESHOLD_OB_MODERATE = 60
RSI_THRESHOLD_OS_MODERATE = 40
RSI_THRESHOLD_OS_STRONG = 30
RSI_NEUTRAL_MARK = 50.0
VOLATILITY_THRESHOLD = 0.02
ATR_PERIOD_DEFAULT = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
MACD_NEUTRAL_MARK = 0.0
MACD_STRENGTH_HIGH = 0.01
MACD_STRENGTH_MED = 0.005

# Risk Management Defaults
RISK_LOW_PORTFOLIO = 0.015
RISK_LOW_POSITION = 0.008
RISK_LOW_MAX_SIZE_USD = 30.0

RISK_HIGH_PORTFOLIO = 0.15
RISK_HIGH_POSITION = 0.10
RISK_HIGH_MAX_SIZE_USD = 80.0

RISK_MEDIUM_PORTFOLIO = 0.08
RISK_MEDIUM_POSITION = 0.04
RISK_MEDIUM_MAX_SIZE_USD = 50.0

MAX_OPEN_POSITIONS = 6
MAX_PORTFOLIO_MARGIN_RATIO = 0.25
DEFAULT_LEVERAGE = 8
LEVERAGE_MIN_OP = 8
LEVERAGE_MAX_OP = 10

# Backtest Configuration
BACKTEST_BASE_PRICE = 100.0
BACKTEST_SEED = 42
TRADING_DAYS_PER_YEAR = 252
MIN_BALANCE_FOR_TRADE = 10.0
MOCK_INITIAL_BALANCE = 1000.0

# System & Monitoring
AUTO_TRAIN_CYCLE_INTERVAL = 12
MAX_POSITIONS_ALERT_THRESHOLD = 4
HTTP_STATUS_ERROR_THRESHOLD = 400
ACCURACY_DRIFT_THRESHOLD = 0.10
PERFORMANCE_ANALYSIS_INTERVAL = 10
CRITICAL_RETURN_THRESHOLD = 10.0
DEFAULT_CYCLE_FREQUENCY_S = 180
MAX_PERFORMANCE_HISTORY = 100
MOMENTUM_ACCELERATION_THRESHOLD = 1.3
MOMENTUM_DECELERATION_THRESHOLD = 0.7
COMMISSION_ROUND_TRIP_MULTIPLIER = 2

# AI & Regime Detection
NEUTRAL_MAJORITY_THRESHOLD = 4
REGIME_DRAWDOWN_THRESHOLD = -5.0
REGIME_PERFORMANCE_THRESHOLD = 5.0
BEARISH_MAX_POSITIONS = 3
BB_EXPANDING_THRESHOLD = 4.0
VOL_RATIO_EXCELLENT = 2.5
VOL_RATIO_GOOD = 1.8
VOL_RATIO_FAIR = 1.2
VOL_RATIO_POOR = 0.2
VOL_RATIO_WEAK = 0.7
VOL_RATIO_STRONG = 1.5
VOL_CONF_CRITICAL = 1.5
FUNDING_RATE_THRESHOLD = 0.0003
COUNTER_TREND_VOL_THRESHOLD = 1.5
VWAP_DISTANCE_THRESHOLD = 2.0
ALIGNMENT_STRENGTH_L1 = 1
ALIGNMENT_STRENGTH_L2 = 2
ALIGNMENT_STRENGTH_L3 = 3
ALIGNMENT_STRENGTH_L4 = 4
ALIGNMENT_STRENGTH_L5 = 5
ALIGNMENT_STRENGTH_L7 = 7
ALIGNMENT_STRENGTH_L8 = 8
ALIGNMENT_STRENGTH_ALL = 3
ALIGNMENT_STRENGTH_MANY = 2
VOLATILE_THRESHOLD_COUNT = 2
CHOPPY_THRESHOLD_COUNT = 3
TRENDING_THRESHOLD_COUNT = 4
REGIME_STRENGTH_THRESHOLD = 0.7

# Account & Validation
BALANCE_UPDATE_THRESHOLD = 0.01
VALUE_SYNC_THRESHOLD = 0.10
NOTIONAL_TIER_1 = 100.0
NOTIONAL_TIER_2 = 200.0
NOTIONAL_TIER_3 = 300.0
NOTIONAL_TIER_4 = 400.0
NOTIONAL_TIER_5 = 500.0
NOTIONAL_TIER_6 = 600.0
MAX_NOTIONAL_USD_TIER = 5000.0

# Indicators & Structure
TREND_SLOPE_THRESHOLD = 0.05
LEVEL_PROXIMITY_THRESHOLD = 2.0
MIN_PEAKS_VALLEYS = 2
RANGE_STRICT_THRESHOLD = 0.015
EXTREME_PERCENTILE_LOW = 10
EXTREME_PERCENTILE_HIGH = 90
STUCK_DATA_PRICE_COUNT = 3
OI_NOT_AVAILABLE_STATUS = 404
PRICE_CACHE_TTL_S = 2.0

# Reversal & Scoring
REVERSAL_SCORE_CRITICAL = 8
REVERSAL_SCORE_STRONG = 5
REVERSAL_SCORE_MODERATE = 3
REVERSAL_SCORE_WEAK = 1
REVERSAL_STRENGTH_MODERATE = 0.5
ENTRY_RATE_AGGRESSIVE = 0.4
CLOSE_RATE_AGGRESSIVE = 0.2
CLOSE_RATE_PROFIT_TAKING = 0.3
PNL_TREND_LOOKBACK = 4
SPARKLINE_TOLERANCE = 0.005
BB_DISTANCE_EXTREME = 2.0
BB_DISTANCE_MODERATE = 1.0
BB_DISTANCE_WEAK = 0.5
EMA_BAND_SENSITIVITY = 0.001
REVERSAL_COUNT_THRESHOLD = 3
PNL_THRESHOLD_NEG = -5.0
PNL_THRESHOLD_POS = 10.0
OI_NOT_AVAILABLE = 404
PRICE_CACHE_TTL = 2.0

# Watch Lists & Tiers
WATCH_CYCLES_LIST = [5, 8, 10]
PROFIT_WATCH_CYCLES_LIST = [5, 8, 10, 12]
MARGIN_TIER_20 = 20.0
MARGIN_TIER_30 = 30.0
MARGIN_TIER_40 = 40.0
MARGIN_TIER_50 = 50.0
LOSS_MULT_BASE = 0.30
LOSS_MULT_L1 = 0.50
LOSS_MULT_L2 = 0.45
LOSS_MULT_L3 = 0.40
LOSS_MULT_L4 = 0.35
PNL_PCT_EXIT_PROFIT = 2.0
PNL_PCT_EXIT_LOSS = -1.5
UNPROFITABLE_COIN_THRESHOLD = -1.0
ENTRY_RATE_AGGRESSIVE = 0.4

# Portfolio Strategy
MIN_DIVERSITY_POSITIONS = 2
MAX_POSITIONS_DIVERSITY = 4
STRENGTH_VERY_HIGH = 0.75
STRENGTH_HIGH = 0.60
STRENGTH_MED = 0.45
STRENGTH_LOW = 0.30
VOLUME_QUALITY_EXCELLENT = 1.8
VOLUME_QUALITY_GOOD = 1.3
VOLUME_QUALITY_FAIR = 0.8
VOLUME_QUALITY_POOR = 0.5

# Performance Monitor Defaults
MAX_SAVED_REPORTS = 50
MIN_HISTORY_FOR_ANALYSIS = 2
SORTINO_MIN_RETURNS = 2
REVERSAL_PCT_HIGH = 50
REVERSAL_PCT_MODERATE = 30

# Metadata & Naming
HTF_DEFAULT_INTERVAL = "1h"
ANN_WINDOW_DEFAULT = 20
PROMPT_SUMMARY_TRUNCATE = 300
PROMPT_SUMMARY_MAX_SECTIONS = 3

# Validation & Config Defaults
MIN_BINANCE_RECV_WINDOW = 1000
MIN_JSON_SERIES_LENGTH = 10
API_KEY_MIN_LENGTH = 8
